id: I5F5600EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:39:29+00:00'
last_modified: '2022-06-07T17:18:49.133256+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7968
  title: གཙང་མ་ཀླུ་འབུམ་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3EE1:
      image_group_id: I1KG3683
      title: ''
      total_pages: 346
      order: 1
      base_file: 3EE1.txt
    9A83:
      image_group_id: I1KG3684
      title: ''
      total_pages: 506
      order: 2
      base_file: 9A83.txt
    B2BD:
      image_group_id: I1KG3685
      title: ''
      total_pages: 492
      order: 3
      base_file: B2BD.txt
    30E0:
      image_group_id: I1KG3686
      title: ''
      total_pages: 510
      order: 4
      base_file: 30E0.txt
    4D4D:
      image_group_id: I1KG3687
      title: ''
      total_pages: 540
      order: 5
      base_file: 4D4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
