id: I5F5600EE
legacy_id: P003064
ocr_import_info:
  bdrc_scan_id: W2CZ7968
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T02:35:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:39:01.244458+00:00'
last_modified: 2022-09-02 23:42:10.602320
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7968
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7968
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཙང་མ་ཀླུ་འབུམ་ཆེན་མོ།
statistics:
  ocr_word_mean_confidence_index: 0.679205021650618
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG3685:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3685
      total_pages: 492
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG3685.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6795165499947398
    legacy_id: v003
  I1KG3686:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3686
      total_pages: 510
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG3686.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6461014139149828
    legacy_id: v004
  I1KG3687:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3687
      total_pages: 540
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG3687.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6479304113157399
    legacy_id: v005
  I1KG3684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3684
      total_pages: 506
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3684.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.687635426630221
    legacy_id: v002
  I1KG3683:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3683
      total_pages: 346
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3683.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7337424313718767
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
